apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: scopewright
    newName: localhost/scopewright
    newTag: latest
patches:
  - path: deployment.yaml
  - path: pvc.yaml
